### ISSUE TITLE
What is the reason to support two versions of notebooks?

### ISSUE THREAD

**Issue by RredCat** [dotnet/csharp-notebooks#13]
I had forked this repository and started to translate it to Ukrainian (the first notebook is done).
But there are two versions of each notebook (dib and ipynb). I don't want to double my work.
Which one is better to choose?
What is the reason to support two versions of notebooks?

**Comment by JakeRadMSFT** [comment]
@RredCat - I'd suggest .ipynb ... it's the most universally supported format.

@jamesmontemagno @katiesavage  Thoughts?

**Comment by JakeRadMSFT** [comment]
@RredCat - I'd suggest .ipynb ... it's the most universally supported format.

@jamesmontemagno @katiesavage  Thoughts?

**Comment by katiesavage** [comment]
+1 on what @JakeRadMSFT said. I would suggest .ipynb

**Comment by JakeRadMSFT** [comment]
I'm removing all the DIB format in this PR:
https://github.com/dotnet/csharp-notebooks/pull/11

**Comment by JakeRadMSFT** [comment]
@RredCat making this as resolved since we only have ipynb now. Let us know once you've translated everything - perhaps we can find a home for them in this repo.
