### ISSUE TITLE
ML Notebooks should use Plotly.NET

### ISSUE THREAD

**Issue by beccamc** [dotnet/csharp-notebooks#44]
Replace XPlot with Plotly.NET.

Blocked on.. 
 -  Plotly.NET getting signed. https://github.com/plotly/Plotly.NET/issues/175
 - Also waiting on C# improvements https://github.com/plotly/Plotly.NET/issues/285

**Comment by kMutagene** [comment]
Both should be resolved: The [newest releases](https://www.nuget.org/packages/Plotly.NET/3.0.0) have strong names and basic native C# bindings are available as well (https://github.com/plotly/Plotly.NET/pull/294, https://www.nuget.org/packages/Plotly.NET.CSharp/).

**Comment by JakeRadMSFT** [comment]
@kMutagene thoughts on the interactive package depending on the CSharp package?

**Comment by kMutagene** [comment]
@JakeRadMSFT what would be the benefit of that other than only referencing one package in C# notebooks. Ideally I would like to keep these packages separated, as that would also mean that an F# notebook using the interactive package would install an unused dependency.

**Comment by JakeRadMSFT** [comment]
Resolved with: https://github.com/dotnet/csharp-notebooks/pull/49
