### ISSUE TITLE
Are ML.NET notebooks using non-public #r nuget references?

### ISSUE THREAD

**Issue by nhirschey** [dotnet/csharp-notebooks#55]
Are the ML.NET notebooks using non-public preview nugets?

I tried to run the first ML.NET notebook [01- Intro to ..](https://github.com/dotnet/csharp-notebooks/blob/b3a808023c492f89a6746ec8ea8b02ef4fd17ea4/machine-learning/01-Intro%20to%20Machine%20Learning.ipynb). I get the following error:

```csharp
#r "nuget: Microsoft.ML, 2.0.0-preview.22356.1"
```
```
C:\Users\nicho\AppData\Local\Temp\nuget\20332--ab38aca3-7c58-4abd-98f6-0079cd1c2c87\Project.fsproj : error NU1102: Unable to find package Microsoft.ML with version (>= 2.0.0-preview.22356.1)
C:\Users\nicho\AppData\Local\Temp\nuget\20332--ab38aca3-7c58-4abd-98f6-0079cd1c2c87\Project.fsproj : error NU1102:   - Found 33 version(s) in nuget.org [ Nearest version: 2.0.0-preview.22313.1 ]
C:\Users\nicho\AppData\Local\Temp\nuget\20332--ab38aca3-7c58-4abd-98f6-0079cd1c2c87\Project.fsproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
```

This is the latest on nuget.org: [#r "nuget: Microsoft.ML, 2.0.0-preview.22313.1"](https://www.nuget.org/packages/Microsoft.ML/2.0.0-preview.22313.1)

**Comment by JakeRadMSFT** [comment]
Oops we must have forgotten to update that one:
If you add this line above the #r lines it'll work.

`#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/MachineLearning/nuget/v3/index.json"`
