### ISSUE TITLE
Alien translator: modify a collection in a foreach loop

### ISSUE THREAD

**Issue by mrlucmorin** [dotnet/csharp-notebooks#62]
The last code block of the Alien translator notebook lacks clarity.

Since you use the same collection variable before and after the foreach loop, it seems like you want the "student" to modify the collection in-place, which is not possible using a foreach loop.

Since the notebook is aimed at new C# programmers, it might be better to hint at a clearer pattern.

Maybe I'm missing something?

**Comment by JakeRadMSFT** [comment]
@mrlucmorin You're right it's a bit odd. I tried a few different ways and a foreach look made it uncomfortable - I'll open a PR. Can you review it?

**Comment by JakeRadMSFT** [comment]
@mrlucmorin the PR is now up: #63
